#!/bin/bash 
set -e 

psql -v ON_ERROR_STOP=1 <<-EOSQL

CREATE ROLE artificial_read WITH LOGIN PASSWORD '$ARTIFICIAL_READ_PASSWORD';
CREATE ROLE artificial_write WITH LOGIN PASSWORD '$ARTIFICIAL_WRITE_PASSWORD';
CREATE ROLE artificial_spool WITH LOGIN PASSWORD '$ARTIFICIAL_SPOOL_PASSWORD';
CREATE ROLE artificial_admin WITH NOLOGIN PASSWORD NULL;
CREATE ROLE sasl WITH LOGIN PASSWORD '$SASL_PASSWORD';
CREATE ROLE postfix WITH LOGIN PASSWORD '$POSTFIX_PASSWORD';

CREATE ROLE thinkulator_read WITH LOGIN PASSWORD '$THINKULATOR_READ_PASSWORD';
CREATE ROLE thinkulator_write WITH LOGIN PASSWORD '$THINKULATOR_WRITE_PASSWORD';
CREATE ROLE thinkulator WITH NOLOGIN PASSWORD NULL;

create database artificial;
create database thinkulator;
EOSQL


